# Generated by Django 5.0.6 on 2024-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_personalinfo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='033e16', max_length=6),
        ),
    ]
