# Generated by Django 5.0.6 on 2024-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_employee_comapany_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='comapany_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2a374d', max_length=6),
        ),
    ]
