# Generated by Django 5.0.6 on 2024-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_comapany_name_employee_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f70b64', max_length=6),
        ),
    ]
