# Generated by Django 5.0.6 on 2024-07-13 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_is_profile_hidden_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_profile_hidden',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hidden_profiles',
            field=models.ManyToManyField(related_name='hidden_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='56c6e2', max_length=6),
        ),
    ]
