# Generated by Django 5.0.6 on 2024-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_otptoken_otp_code_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b21bb8', max_length=6),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
