# Generated by Django 5.0.6 on 2024-07-16 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_otptoken_otp_code_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_profiles',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='092658', max_length=6),
        ),
    ]
