# Generated by Django 5.0.6 on 2024-07-16 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_liked_profiles_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_by_profiles',
            field=models.ManyToManyField(blank=True, related_name='liked_profiles_reverse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fb2e20', max_length=6),
        ),
    ]
